name: heatmap-hackathon
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - geopandas
  - shapely
  - pyproj
  - contextily
  - folium
  - scikit-learn
  - pip
  - pip:
      - python-dotenv
